import { Nunito } from 'next/font/google';
import ClientOnly from './components/ClientOnly';
import Navbar from './components/navbar/Navbar';
import './globals.css';

export const metadata = {
  title: 'YokoDom',
  description: 'Generated by create next app',
};

const fonts = Nunito({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={fonts.className}>
        <ClientOnly>
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
